name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v2
    - uses: docker://allesrebel/nrf52-dev-env:latest
