on:
  push:
    branches:
    - master
    - release/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Try to Build
        uses: docker://allesrebel/nrf52-dev-env:latest
        with:
          volumns: $GITHUB_WORKSPACE:/opt/project
